apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/environment: staging
  app.kubernetes.io/version: "1.0"

bases:
- ../../base

namespace: playground-staging

images:
- name: gcr.io/substrateplayground-252112/jeluard/substrate-playground
  digest: sha256:196cc9171a3c533dac97001a3e4b1bd985979a69e817fac9f51d6ed9d0f6f394

patches:
- custom-load-balancer-ip.yaml

patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: ingress
  path: ingress-patch.yaml