apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/environment: staging
  app.kubernetes.io/version: "1.0"

namespace: playground-staging

resources:
- ../../base

images:
- name: gcr.io/substrateplayground-252112/jeluard/substrate-playground-backend-api
  digest: sha256:df7834168005a40f65f856bded0eca884196542fe1755b6b9e4b92a35ac6d84d
- name: gcr.io/substrateplayground-252112/jeluard/substrate-playground-backend-ui
  digest: sha256:f39b52c471485ade235d0b3105d146bbcfb15e37a6219862d07524c2b27222eb

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: playground-staging.substrate.dev
  target:
    group: extensions
    kind: Ingress
    name: ingress
    version: v1beta1

patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: Service
  metadata:
    name: ingress-nginx
    namespace: ingress-nginx
  spec:
    loadBalancerIP: 34.69.4.59
- |-
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: ingress
  spec:
    tls:
    - hosts:
      - '*.playground-staging.substrate.dev'
      secretName: playground-tls
