apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/environment: staging
  app.kubernetes.io/version: "1.0"

bases:
- ../../base

resources:
- namespace.yaml

namespace: playground-staging

images:
- name: gcr.io/substrateplayground-252112/jeluard/substrate-playground
  digest: sha256:41294e53f7fc7c0c3edcce278b1b031bcaf5fe51eabc2d23052692e653acb73d

patches:
- custom-load-balancer-ip.yaml

patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: ingress
  path: ingress-patch.yaml