{
    "kind": "Service",
    "apiVersion": "v1",
    "metadata": {
        "generateName": "theia-substrate-http-",
        "labels": {
            "app": "theia-substrate",
            "app-uuid": "%UUID%"
        }
    },
    "spec": {
        "ports": [
            {
                "name": "theia-http",
                "protocol": "TCP",
                "port": 8080
            },
            {
                "name": "node-http",
                "protocol": "TCP",
                "port": 8000
            },
            {
                "name": "tcp",
                "protocol": "TCP",
                "port": 30333
            },
            {
                "name": "ws",
                "protocol": "TCP",
                "port": 9933
            },
            {
                "name": "wss",
                "protocol": "TCP",
                "port": 9944
            }
        ],
        "selector": {
            "app-uuid": "%UUID%"
        },
        "type": "LoadBalancer"
    }
}