{
    "kind": "Service",
    "apiVersion": "v1",
    "metadata": {
        "generateName": "theia-substrate-http-",
        "labels": {
            "app": "theia-substrate",
            "app-uuid": "%UUID%"
        }
    },
    "spec": {
        "ports": [
            {
                "protocol": "TCP",
                "port": 8080
            }
        ],
        "selector": {
            "app-uuid": "%UUID%"
        },
        "type": "LoadBalancer"
    }
}