[book]
authors = ["Julien Eluard"]
language = "en"
multilingual = false
src = "."
title = "Playground"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-css = ["mermaid.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]