[[bin]]
name = "playground"

[package]
name = "playground"
version = "0.1.0"
authors = ["jeluard <julien@parity.io>"]
edition = "2018"

[dependencies]
log = "0.4.8"
rocket = "0.4.2"
rocket_cors = "0.5.0"

[dependencies.rocket_contrib]
version = "0.4.2"
features = ["json"]