[[bin]]
name = "playground"

[package]
name = "playground"
version = "0.1.0"
authors = ["jeluard <julien@parity.io>"]
edition = "2018"

[dependencies]
log = "0.4.8"
env_logger = "0.6.2"
timer = "0.2.0"
chrono = "0.4.9"
toml = "0.5.3"
uuid = { version = "0.7", features = ["v4"] }
rocket = "0.4.2"
rocket_cors = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.40"
kube = { git = "https://github.com/clux/kube-rs", features = ["openapi"] }
k8s-openapi = { version = "0.5.1", default-features = false, features = ["v1_15"] }

[dependencies.rocket_contrib]
version = "0.4.2"
features = ["json"]