apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/environment: dev
  app.kubernetes.io/version: "1.0"

resources:
- ../../base
- templates.yaml
- users.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: playground-config
    literals:
    # Github client ID can be safely shared publicly.
    # Also it is specific to this dev env whose TLD can't be registered (.test).
    - github.clientId=dd81163290c118582a1a
    - session.defaultDuration=180
    - session.defaultPoolAffinity=default
    - session.defaultMaxPerNode=2

images:
- name: paritytech/substrate-playground-backend-api
  newTag: latest
- name: paritytech/substrate-playground-backend-ui
  newTag: latest

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: playground-dev.substrate.test
  target:
    group: networking.k8s.io
    kind: Ingress
    name: ingress
    version: v1beta1
