apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/environment: dev
  app.kubernetes.io/version: "1.0"

resources:
- ../../base
- templates.yaml
- users.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: playground-config
    literals:
    # Github client ID can be safely shared publicly.
    # Also it is specific to this dev env whose TLD can't be registered (.test).
    - github.clientId=dd81163290c118582a1a
    - session.defaultDuration=180
    - session.defaultPoolAffinity=default
# TODO make immutable
# Requires k8s 1.19
# See https://github.com/kubernetes-sigs/kustomize/issues/2895
# and https://kubernetes.io/docs/concepts/configuration/configmap/#configmap-immutable
#generatorOptions:
#  immutable: true

secretGenerator:
  - name: playground-secrets
    literals:
    # Both secrets are safe to be stored in repository as they are specific to this dev env whose TLD can't be registered (.test).
    - github.clientSecret=abdcf38dd290429b98f43074d010b989cf970461
    - rocket.secretKey=tNxYqkQ5o9KiT8mQPVxqxu+H2Sl+Jd4CxkpFZmkw6Kw=

images:
- name: paritytech/substrate-playground-backend-api
  newTag: latest
- name: paritytech/substrate-playground-backend-ui
  newTag: latest

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: playground-dev.substrate.test
  target:
    group: networking.k8s.io
    kind: Ingress
    name: ingress
    version: v1beta1
