
apiVersion: v1
kind: ConfigMap
metadata:
  name: templates
data:
  recipes: |
    image: paritytech/substrate-playground-template-test-theia:latest
    name: Test
    description: 'A stock template'
    public: true
    runtime:
      ports:
        - name: wss
          protocol: TCP
          path: /wss
          port: 9944
