apiVersion: v1
kind: ServiceAccount
metadata:
  name: default-service-account
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-role
subjects:
- kind: ServiceAccount
  name: default-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground
spec:
  selector:
    matchLabels:
      app: playground
  replicas: 1
  template:
    metadata:
      labels:
        app: playground
    spec:
      serviceAccountName: default-service-account
      containers:
      - name: playground
        image: jeluard/substrate-playground@sha256:aac05bd08c8cf7ec42e207caf2c3bad6a1057c4ec1a5fbde6bc79fd8c8578da8
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: playground-http
  labels:
    app: playground
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  loadBalancerIP: "35.202.224.243"
  selector:
    app: playground
