
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: prometheus
resources:
- deployment.yaml
- rbac.yaml
- service.yaml
- volume.yaml
images:
- name: prom/prometheus
  newTag: v2.22.1
configMapGenerator:
- name: prometheus-configuration
  files:
  - prometheus.yaml