name: Build Book

on:
  push:
    branches:
    - master
    - develop
    paths:
    - '.github/workflows/book.yml'
    - 'docs/**'

jobs:
  build-and-publish-book:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        config-file: '.github/workflows/mlc_config.json'

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1

    - name: Install linkcheck
      run: cargo install mdbook-linkcheck

    - name: Build Book
      run: mdbook build
      working-directory: ./docs

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/book/html
