name: Continuous Deployment Templates staging

on:
  push:
    branches:
      - develop
    paths:
      - 'templates/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy templates
        run: make k8s-update-images-config
        env:
          ENVIRONMENT: staging
          SKIP_ACK: true