name: Continuous Deployment Playground staging

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'templates/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          persist-credentials: false
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          # GCLOUD_KEY is the base64 of the gcloud service account JSON file
          # Get the JSON file from https://console.cloud.google.com/iam-admin/serviceaccounts?authuser=1&hl=fr&project=substrateplayground-252112&folder=&organizationId=&supportedpurview=project
          # ... -> Actions -> Create Key
          # then base64 substrateplayground-XXX.json | tr -d \\n
          service_account_key: ${{ secrets.GCLOUD_KEY }}
          export_default_credentials: true
      - run: gcloud auth configure-docker
      - run: echo "::set-env name=ACCESS_TOKEN::$(gcloud auth print-access-token)"
      - uses: docker/build-push-action@v1 # https://github.com/docker/build-push-action
        with:
          username: oauth2accesstoken
          password: ${{ env.ACCESS_TOKEN }}
          dockerfile: conf/Dockerfile
          repository: substrateplayground-252112/jeluard/substrate-playground
          registry: gcr.io
          tags: latest
          add_git_labels: true
          tag_with_ref: true
          tag_with_sha: true
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.5.5/kustomize_v3.5.5_linux_amd64.tar.gz
          tar zxvf kustomize*
          chmod u+x ./kustomize  
        working-directory: conf/k8s/overlays/staging
      - name: Update version
        run: ./kustomize edit set image gcr.io/substrateplayground-252112/jeluard/substrate-playground:sha-${GITHUB_SHA::7}
        working-directory: conf/k8s/overlays/staging
      - uses: stefanzweifel/git-auto-commit-action@v4.2.0
        with:
          commit_message: "ci: Updated playground image"
      - name: Deploy on GKE
        run: ./kustomize build conf/k8s/overlays/staging/ | kubectl apply --record -f -