name: Build website

on:
  push:
    branches:
    - master
    - develop
    paths:
    - '.github/workflows/cd-documentation.yml'
    - 'website/**'

jobs:
  build-and-publish-book:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Build website
      run: yarn build
      working-directory: ./website

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./website/build
