name: Continuous Integration Templates

on:
  pull_request:
    paths:
      - '.github/workflows/ci-templates.yml'
      - 'templates/**'

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
      # https://github.com/actions/setup-node
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install
        run: yarn install --check-files
        working-directory: ./templates
      - name: Build
        run: yarn workspace @parity/theia-playground theia build
        working-directory: ./templates
