name: Continuous Integration Templates

on:
  pull_request:
    paths:
      - '.github/workflows/ci-templates.yml'
      - 'templates/*'

jobs:
  templates:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[CI Skip]')"
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"

      - name: Install
        run: yarn install --check-files
        working-directory: ./templates

      - name: Build
        run: yarn workspace @parity/theia-playground theia build
        working-directory: ./templates
